Improved UseClickOutside HOOK's behaviour.
mindbox-moscow/ui-kit pull request #1088
Opened 2020-08-28 11:50 UTC by devgavrilov

https://github.com/mindbox-moscow/issues-dev2/issues/286

2020-08-31 08:55 UTC, Deadoc commented on src/HOOKs/useClickOutside/useClickOutside.tsx
> +		preventHandlerCall = preventHandlerCall || ref.current != null && ref.current.contains(e.target as HTMLElement);
Кажется тут preventHandlerCall || можно дропнуть

2020-08-31 08:55 UTC, Deadoc commented on src/HOOKs/useClickOutside/useClickOutside.tsx
> +		preventHandlerCall = preventHandlerCall || ref.current != null && ref.current.contains(e.target as HTMLElement);
А давай каждую отдельную строчку вынесем в функцию с понятным именем?
Сейчас очень тяжело понять что конкретно ты хочешь проверить

2020-08-31 09:18 UTC, devgavrilov commented on src/HOOKs/useClickOutside/useClickOutside.tsx
> +		preventHandlerCall = preventHandlerCall || ref.current != null && ref.current.contains(e.target as HTMLElement);
> Кажется тут preventHandlerCall || можно дропнуть
Подскажи - как можно дропнуть? Просто оператора `||=` нет, а оператор `|=` работает с числами. Технически, можно подхачить под последний вариант, но чёт не очень.

2020-08-31 10:50 UTC, Deadoc commented on src/HOOKs/useClickOutside/useClickOutside.tsx
> +				document.addEventListener("mousedown", handleMouseDown);
Это же не одно и тоже

2020-08-31 10:50 UTC, Deadoc commented on src/HOOKs/useClickOutside/useClickOutside.tsx
> +				document.addEventListener("mousedown", handleMouseDown);
Похоже что логика меняется

2020-08-31 11:10 UTC, devgavrilov commented on src/HOOKs/useClickOutside/useClickOutside.tsx
> +				document.addEventListener("mousedown", handleMouseDown);
Да. Раньше было так:
- Если человек _отпустил_ (поднял) кнопку мыши на элементе - событие `click`, который подходит под правила выше, то `handler` не вызывается и окно не закрывается (то, что вешается на `handler`).

Сейчас это сделано так: 
- Если человек _нажал_ кнопку мыши на элементе, который подходит под правила выше, то handler не вызывается.

Мотивация:
Если ты взаимодействуешь с элементоми и _нажмёшь_ кнопкой мыши внутри элемента, а _отпустишь_ кнопку за его пределами, то в первом случае вызовется `handler` и окно закроется. Во втором случае `handler` вызван не будет.

2020-09-02 08:21 UTC, KlonD90 commented on src/HOOKs/useClickOutside/useClickOutside.tsx
> +				document.addEventListener("mousedown", handleMouseDown);
Но тогда ведь и клика не будет если ты нажал на одном элементе а закончил на другом

2020-09-02 08:23 UTC, devgavrilov commented on src/HOOKs/useClickOutside/useClickOutside.tsx
> +				document.addEventListener("mousedown", handleMouseDown);
А событие вызывается в таком случае. Когда отпускаешь ПКМ, вызывается событие `click` на элементе, где ты отпустил ПКМ.

2020-09-02 08:24 UTC, KlonD90 commented on src/HOOKs/useClickOutside/useClickOutside.tsx
> +				document.addEventListener("mousedown", handleMouseDown);
А понял. Это будет click на ближайшем общем предке.

2020-09-02 08:28 UTC, devgavrilov commented on src/HOOKs/useClickOutside/useClickOutside.tsx
> +	const isEventWasInvokenOnElementWithNeutralZoneClass = (e: MouseEvent) => ignoreNeutralZoneClass ? false : fromElementWithClassEvent(e, exports.neutralZoneClass);
isEventWasInvoken -> isEventWasInvoked

2020-09-02 08:34 UTC, KlonD90 requested changes

2020-09-02 08:34 UTC, KlonD90 commented on src/HOOKs/useClickOutside/useClickOutside.tsx
>  			} else {
else ветка здесь никогда не сработает, потмоу что каждый раз создаются уникальные хэндлеры. Так что можно иметь одну ветку на subscribed и на отписку

2020-09-02 08:34 UTC, KlonD90 commented on src/HOOKs/useClickOutside/useClickOutside.tsx
> +	const isEventWasInvokedOnCurrentElementOrChildren = (e: MouseEvent) => ref.current != null && ref.current.contains(e.target as HTMLElement);
функции стоит сделать чистыми и перенести за пределы самого хука, чтобы не создавать их каждый раз

2020-09-02 08:34 UTC, KlonD90 commented on src/HOOKs/useClickOutside/useClickOutside.tsx
>  				document.addEventListener("click", listener);
определение listener и handleMouseDown имеет смысл внести внутрь этого callback чтобы не создавать их на каждый раунд, но это вполне оверкилл можно пропустить

2020-09-02 08:34 UTC, KlonD90 commented on src/HOOKs/useClickOutside/useClickOutside.tsx
> +				document.removeEventListener("mousedown", handleMouseDown);
имеет смысл тогда touchstart сюда же добавить

2020-09-02 08:38 UTC, devgavrilov commented on src/HOOKs/useClickOutside/useClickOutside.tsx
> +	const isEventWasInvokedOnCurrentElementOrChildren = (e: MouseEvent) => ref.current != null && ref.current.contains(e.target as HTMLElement);
Функции вынесу. А что ты подразумеваешь под "чистыми"?

2020-09-02 08:56 UTC, KlonD90 commented on src/HOOKs/useClickOutside/useClickOutside.tsx
> +	const isEventWasInvokedOnCurrentElementOrChildren = (e: MouseEvent) => ref.current != null && ref.current.contains(e.target as HTMLElement);
Что они не читают данные из замыканий, а только то что передано как аргументы

2020-09-02 15:03 UTC, devgavrilov commented on src/HOOKs/useClickOutside/useClickOutside.tsx
>  			} else {
Т.е. переменная `shouldBeSubscribed` в принципе бесполезная и её выпиливаю?

2020-09-04 07:12 UTC, merged